### ISSUE TITLE
Error when using the mod

### ISSUE THREAD

**Issue by LisaBleik** [MathIsFun0/Talisman#20]
Error

Syntax error: game.lua:4: '=' expected near 'Game'

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: at 0x7ff80aa49a00
[C]: in function 'require'
main.lua:16: in main chunk
[C]: in function 'require'
[[[[C]: in function 'xpcall'''
[[[[C]: in function 'xpcall'''

**Comment by MathIsFun0** [comment]
Check that you do not have a conflicting installation of Steamodded, by verifying game integrity in Steam.
