### ISSUE TITLE
Conflict with Steamodded's quick restart

### ISSUE THREAD

**Issue by Aurelius7309** [MathIsFun0/Talisman#28]
Steamodded needs to kill threads when restarting or they won't work afterwards. Talisman overrides the save manager thread completely using a string, thus invalidating Steamodded's kill signal. This causes no game settings and run data to be saved after a restart. Please switch to patching `engine/save_manager.lua` or at least include the kill signal in the override

**Comment by MathIsFun0** [comment]
I've switched to patching.
